### ISSUE TITLE
[Bug] workflows/ folder is not found

### ISSUE THREAD

**Issue by w9w** [projectdiscovery/nuclei-templates#1120]
root@sweet-muffin:~# nuclei -t workflows/ -silent -target https://website.com
[FTL] Error, no templates were found.

While all other template folders exist for nuclei, it seems like a bug, the latest version.

**Comment by geeknik** [comment]
Hi, you'll need to use the `-w` or `-workflows` flag for workflows in the newest version of nuclei. 👍🏻

**Comment by w9w** [comment]
Hi @geeknik! I don't see -w in the documentation. Could you please specify how to define the flag? nuclei -w workflows/wordpress-workflow.yaml, nuclei -w wordpress-workflow.yaml and nuclei -w workflows/wordpress don't work.

Also, is it possible to keep the old call to workflows with the -t flag? I have tens of mentions with this flag in my private workflow script, and I have to rewrite everything.

**Comment by geeknik** [comment]
Make sure you are running nuclei 2.3.1 as I see `-w` at the bottom of the `nuclei -h` output.  

Running `nuclei -w nuclei-templates/workflows/ -target https://twitter.com/` results in this output:
```
[INF] Loading templates...
[INF] Loading workflows...
[INF] [magmi-workflow] MAGMI Security Checks (@dwisiswant0)
[INF] [springboot-workflow] Springboot Security Checks (@dwisiswant0)
[INF] [rabbitmq-workflow] RabbitMQ Security Checks (@fyoorer)
[INF] [vbulletin-workflow] vBulletin Security Checks (@pdteam)
[INF] [jira-workflow] Jira Security Checks (@micha3lb3n)
[INF] [sap-netweaver-workflow] SAP NetWaver Security Checks (@dwisiswant0)
[INF] [cisco-asa-workflow] Cisco ASA Security Checks (@flag007)
[INF] [mida-eframework-workflow] Mida eFramework Security Checks (@CasperGN)
[INF] [liferay-workflow] Liferay Security Checks (@dwisiswant0)
[INF] [wordpress-workflow] Wordpress Security Checks (@kiblyn11 & zomsop82)
[INF] [lotus-domino-workflow] Lotus Domino Security Checks (@CasperGN)
[INF] [harbor-workflow] Harbor Security Checks (@pikpikcu)
[INF] [artica-web-proxy-workflow] Artica Web Proxy Security Checks (@dwisiswant0 & pdteam)
[INF] [micro-focus-workflow] Micro Focus Checks (@dwisiswant0)
[INF] [samsung-wlan-ap-workflow] Samsung Wlan AP (WEA453e) Checks (@pikpikcu)
[INF] [netsweeper-workflow] Netsweeper Security Checks (@dwisiswant0)
[INF] [thinkcmf-workflow] ThinkCMF Security Checks (@pdteam)
[INF] [dell-idrac-workflow] Dell iDRAC Security Checks (@kophjager007)
[INF] [solarwinds-orion-workflow] SolarWinds Orion Security Checks (@dwisiswant0)
[INF] [thinkphp-workflow] ThinkPHP Security Checks (@dr_set)
[INF] [weblogic-workflow] WebLogic Security Checks (@dr_set)
[INF] [grafana-workflow] Grafana Security Checks (@pdteam)
[INF] [cacti-workflow] Cacti Checks (@pikpikcu)
[INF] [bigip-workflow] F5 BIG-IP Security Checks (@dwisiswant0)
[INF] Using 24 rules (0 templates, 24 workflows)
[INF] No results found. Better luck next time!
```

**Comment by w9w** [comment]
@geeknik, I updated to the latest version. However, I can't go through only 1 workflow, - instead, all templates are activated for the target:

nuclei -w nuclei-templates/workflows/wordpress-workflow.yaml -silent -target https://twitter.com
[2021-03-21 17:02:46] [general-tokens] [http] [medium] https://twitter.com [Token":"5d7827dfadc1ffe1f49da855ffeecf18cfde4c5b"]
[2021-03-21 17:02:46] [mx-service-detector:Google Apps] [dns] [info] https://twitter.com
[2021-03-21 17:02:46] [generic-tokens] [http] [info] https://twitter.com [Token":"5d7827dfadc1ffe1f49da855ffeecf18cfde4c5b"]

**Comment by w9w** [comment]
I can't reach the same result as you showed, even with workflows hosted in the different directory and specifying them. Maybe you have a modified version of the program?

**Comment by geeknik** [comment]
Well, I am running the dev branch of nuclei, so there is always the chance a bug was fixed in between releases.

If you'd like to try the dev branch, here is how I build it:
```
git clone https://github.com/projectdiscovery/nuclei
git checkout dev
cd nuclei/v2/cmd/nuclei
go get -u
go build
mv nuclei $HOME/go/bin/
```
If that doesn't work or you don't want to muck around with non-release builds, maybe @ehsandeep can shed some light.

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/nuclei/pull/636 this has been fixed in the master code.

**Comment by w9w** [comment]
@ehsandeep, I deleted nuclei and made sure it's deleted. Then I installed your newly added version. The issue still persists:

root@sweet-muffin:~/scripts/update-golang# nuclei -w anystring -silent -target https://twitter.com
[2021-03-21 18:27:29] [general-tokens] [http] [medium] https://twitter.com [Token":"5d7827dfadc1ffe1f49da855ffeecf18cfde4c5b"]
[2021-03-21 18:27:29] [generic-tokens] [http] [info] https://twitter.com [Token":"5d7827dfadc1ffe1f49da855ffeecf18cfde4c5b"]

No matter what input is passed to the -w flag, nuclei will enumerate all templates.

**Comment by w9w** [comment]
I'll try to install the dev version

**Comment by w9w** [comment]
Same situation with the dev branch:

root@sweet-muffin:~/scripts/nuclei# git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
root@sweet-muffin:~/scripts/nuclei# cd v2/cmd/nuclei
root@sweet-muffin:~/scripts/nuclei/v2/cmd/nuclei# go get -u
go: downloading go.uber.org/ratelimit v0.2.0
go: downloading github.com/projectdiscovery/clistats v0.0.8
go: downloading github.com/go-rod/rod v0.96.0
go: downloading github.com/projectdiscovery/fastdialer v0.0.9
go: downloading golang.org/x/crypto v0.0.0-20210317152858-513c2a44f670
go: downloading github.com/miekg/dns v1.1.41
go: downloading golang.org/x/net v0.0.0-20210316092652-d523dce5a7f4
go: downloading github.com/xanzy/go-gitlab v0.47.0
go: downloading golang.org/x/oauth2 v0.0.0-20210313182246-cd4f82c27b84
go: downloading github.com/ysmood/leakless v0.6.14
go: downloading golang.org/x/sys v0.0.0-20210320140829-1e4c9ba3b0c4
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/golang/snappy v0.0.3
go: downloading github.com/golang/protobuf v1.5.1
go: downloading google.golang.org/protobuf v1.26.0
go: downloading github.com/andres-erbsen/clock v0.0.0-20160526145045-9e14626cd129
go get: upgraded github.com/go-rod/rod v0.91.1 => v0.96.0
go get: upgraded github.com/golang/protobuf v1.4.3 => v1.5.1
go get: upgraded github.com/golang/snappy v0.0.2 => v0.0.3
go get: upgraded github.com/miekg/dns v1.1.38 => v1.1.41
go get: upgraded github.com/projectdiscovery/clistats v0.0.7 => v0.0.8
go get: upgraded github.com/projectdiscovery/fastdialer v0.0.8 => v0.0.9
go get: upgraded github.com/xanzy/go-gitlab v0.44.0 => v0.47.0
go get: upgraded go.uber.org/ratelimit v0.1.0 => v0.2.0
go get: upgraded golang.org/x/crypto v0.0.0-20210218145215-b8e89b74b9df => v0.0.0-20210317152858-513c2a44f670
go get: upgraded golang.org/x/net v0.0.0-20210119194325-5f4716e94777 => v0.0.0-20210316092652-d523dce5a7f4
go get: upgraded golang.org/x/oauth2 v0.0.0-20210218202405-ba52d332ba99 => v0.0.0-20210313182246-cd4f82c27b84
go get: upgraded golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9 => v0.0.0-20210220032951-036812b2e83c
go get: upgraded golang.org/x/sys v0.0.0-20210218155724-8ebf48af031b => v0.0.0-20210320140829-1e4c9ba3b0c4
go get: upgraded golang.org/x/time v0.0.0-20201208040808-7e3f01d25324 => v0.0.0-20210220033141-f8bda1e9f3ba
root@sweet-muffin:~/scripts/nuclei/v2/cmd/nuclei# go build
root@sweet-muffin:~/scripts/nuclei/v2/cmd/nuclei# mv nuclei $HOME/go/bin/
root@sweet-muffin:~/scripts/nuclei/v2/cmd/nuclei# nuclei

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.1

		projectdiscovery.io

[FTL] Program exiting: no template/templates provided
root@sweet-muffin:~/scripts/nuclei/v2/cmd/nuclei# nuclei -w workflows/wordpress-workflow.yaml -silent -target https://twitter.com
[2021-03-21 18:36:16] [general-tokens] [http] [medium] https://twitter.com [Token":"5d7827dfadc1ffe1f49da855ffeecf18cfde4c5b"]
[2021-03-21 18:36:16] [generic-tokens] [http] [info] https://twitter.com [Token":"5d7827dfadc1ffe1f49da855ffeecf18cfde4c5b"]

**Comment by ehsandeep** [comment]
@w9w this should work for you till the time we publish the new release for nuclei

```
git clone https://github.com/projectdiscovery/nuclei.git; \
cd nuclei/v2/cmd/nuclei; \
go build; \
./nuclei -ut; \
./nuclei -w workflows/wordpress-workflow.yaml -silent -target https://eng.uber.com
```

**Comment by w9w** [comment]
Much thanks @ehsandeep, it works now, and I can continue to hack!

Thank you, and have a beautiful day, Max (@w2w).

**Comment by w9w** [comment]
A program doesn't seem to see workflows in different directories (it's not a typo). My private workflow contains private templates; could you please specify how to edit native templates?

/root/scripts/nuclei/v2/cmd/nuclei/./nuclei -w /root/scripts/nuclei_templates/workflows/wordpress-workflow.yaml -silent -target https://eng.uber.com
[FTL] Error, no templates were found.

**Comment by w9w** [comment]
One way to solve the problem is to downgrade to the previous version where statement -t workflow/name.yaml works.

**Comment by w9w** [comment]
2.1.0 release doesn't work, too. Although before, it worked fine, at least for usual templates (not workflows).

A command ./nuclei -t /root/scripts/nuclei_templates/workflows/wordpress-workflow.yaml -silent -target https://eng.uber.com
returns no output, even no errors.

**Comment by ehsandeep** [comment]
@w9w not sure what wrong on your side, it works here! also, you can always use `-v` flag to see additional error details.

```
./nuclei -w ~/GitHub/test/wordpress-workflow.yaml -target https://eng.uber.com

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.1

		projectdiscovery.io

[INF] Loading templates...
[INF] Loading workflows...
[INF] [wordpress-workflow] Wordpress Security Checks (@kiblyn11 & zomsop82)
[INF] Using 1 rules (0 templates, 1 workflows)
[0:00:01] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 0/1 (0%)
[0:00:02] | Templates: 1 | Hosts: 1 | RPS: 0 | Matched: 0 | Errors: 0 | Requests: 1/84 (1%)
[2021-03-22 12:29:57] [wp-license-file] [http] [info] https://eng.uber.com/license.txt
```

**Comment by w9w** [comment]
@ehsandeep thanks, I'll check in the evening.

**Comment by ehsandeep** [comment]
@w9w [v3.2.2](https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.2) is out now, update to the latest version and everything gonna be alright.

**Comment by w9w** [comment]
@ehsandeep, nuclei sees the custom directories now; thanks a lot! 👍
